### ISSUE TITLE
Capitalization typo in copydoc directives to GridHander

### ISSUE THREAD

**Issue by ctgraham** [pkp/customBlockManager#19]
On 
https://github.com/pkp/customBlockManager/blob/f1852e25279ea21b027e49baab4f6a8a6689d50a/controllers/grid/CustomBlockGridHandler.inc.php#L40
and
https://github.com/pkp/customBlockManager/blob/f1852e25279ea21b027e49baab4f6a8a6689d50a/controllers/grid/CustomBlockGridHandler.inc.php#L93

"Gridhandler" instead of "GridHander"

**Comment by bozana** [comment]
Can the issue be closed now?
