### ISSUE TITLE
callbackLoadCategory() is obsolete

### ISSUE THREAD

**Issue by ctgraham** [pkp/customBlockManager#43]
The method `CustomBlockManagerPlugin::callbackLoadCategory()` is obsolete and unused after pkp/pkp-lib#3336 moved the block registration into `register()`:
https://github.com/pkp/customBlockManager/commit/ec5838a0c601d75c86f6d72a0ed8ac9f0cd09bba

**Comment by asmecher** [comment]
Resolved -- thanks, @ctgraham!
