### ISSUE TITLE
Blocked Block plugin

### ISSUE THREAD

**Issue by jafamo** [pkp/customBlockManager#50]
Hi, 
I am using ojs_3_1_1_4 with more than 100 journals.
I have some plugins with a particular order in my sidebar, do you know if can I locked this plugins in all my journals?
I would like to lock only this 3  blockPlugins always on the same position.

I can insert my plugins on code, but I don't know where, maybe in _BlockPluginsListbuilderHandler_ 

Can I call my plugins on any Handler to lock position ?
ex
{call_hook name=".........."}

Regards.
jafamo

**Comment by asmecher** [comment]
@jafamo, could you post your question on our support forum at https://forum.pkp.sfu.ca? That's the best place for Q&A, either editorial or technical. This is more for bug reports and feature discussion.
