### ISSUE TITLE
Custom Block Manager error to save if the content image?

### ISSUE THREAD

**Issue by nasseer66** [pkp/customBlockManager#79]
Hello,
When I try to add a new item under Custom Blocks, the information is not saved if the content image is uploaded or is an external URL.
The Save button becomes light gray but not saved.
All add new item work normally if they are only texts.

I use :OJS 3.4.0-1

**Comment by asmecher** [comment]
I see this is cross-posted on the support forum:

https://forum.pkp.sfu.ca/t/ojs-3-4-0-1-custom-block-manager-error-to-save-if-the-content-image/79885

@nasseer66, it's best to pick just one place to post; the forum is a good place to start in the future. I'll close this issue as the forum post has already been resolved.
