### ISSUE TITLE
Custom Block Manager  Loading

### ISSUE THREAD

**Issue by Syamsulalamraml** [pkp/customBlockManager#81]
![Screenshot (2351)](https://github.com/pkp/customBlockManager/assets/154288240/fb476127-ce8b-4605-9a0a-0eace664a6f2)

ada yang bisa bantu saya untuk mengatasi masalah ini " Custom Block Manager  Loading"

**Comment by asmecher** [comment]
@Syamsulalamraml, can you check your PHP error log to see if it has any relevant details?

(In the future, I'd recommend posting on our [Community Forum](https://forum.pkp.sfu.ca/); that's the best place to get help.)

**Comment by Syamsulalamraml** [comment]
terima kasih. informasinya Pak. saya sudah mendapatkan permasaalhannya di bagian CustomBlockManagerPlugin.php

ternyata permasalahan di  kode: Hook::add('LoadComponentHandler', $this->setupGridHandler(...));

saya mengganti kode menjadi: Hook::add('LoadComponentHandler', [$this, 'setupGridHandler']);

berikut hasil yang sudah saya ganti:

                // This hook is used to register the components this plugin implements to
                // permit administration of custom block plugins.
                Hook::add('LoadComponentHandler', [$this, 'setupGridHandler']);

sumber: https://github.com/pkp/customBlockManager/commit/e3a2b3b56b8600082a0fea1c38e47c3833f98ab8

**Comment by asmecher** [comment]
@Syamsulalamraml, it sounds like you might be using a version of the plugin code that's not intended for your version of OJS/OMP/OPS. If you're using OJS 3.3.0, make sure to use the stable-3_3_0 branch of this repository -- or better yet, just use the Plugin Gallery to install the plugin.
